

## Rethinking What It Means to Do Good Science in Social Science Research

I keep rethinking the meaning of conducting rigorous and meaningful research in the social sciences after reading How to Be a Modern Scientist by Jeff Leek (2016). 

One of the main takeaways is the importance of reproducibility in modern social science. Almost all of the data I use are private administrative data. When preparing manuscripts, the common approach is to include a standardized statement under “Data Availability” noting that “we are unable to provide the data used in this work because it contains confidential information. However, this does not prevent us from conveying the main purpose and key contributions of the paper.” While doing this, I sometimes felt that it was a bit awkward, but it seemed that there was no other solution in this situation. 

Leek, however, mentioned two potential strategies in the book: defining a process for accessing the data and providing a mechanism for verification (p. 26), and I think these strategies are feasible. For private data, we could provide data access instructions, such as the application process, data use agreements, and conditions for data use, so that qualified external researchers can legally obtain the data. In addition, we could provide code and analysis scripts so that external researchers can verify the results. Even though these practices cannot be implemented in a journal article, we can still do this in a blog or on GitHub, which is uncommon in social science research. 

Reference: Leek, J. (2016). How to be a modern scientist. Leanpub.





----